version: "3.8"

services:
  taskapi:
    build: /taskapi
    container_name: taskapi
    command: uvicorn app:app --host 0.0.0.0 --port ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - ./.env:/.env
    networks:
      network:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    command: postgres -p ${DATABASE_PORT}
    ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      network:

networks:
  network:
